Repository TPC-Council/HammerDB, pull requests merged in 2023-10, with the labels that each got.

#610 Fix for TPROC-H calculates o_totalprice incorrectly
  src/db2/db2olap.tcl
  src/mariadb/mariaolap.tcl
  src/mssqlserver/mssqlsolap.tcl
  src/mysql/mysqlolap.tcl
  src/oracle/oraolap.tcl
  src/postgresql/pgolap.tcl
Labels: bug

#599 Fix MySQL/MariaDB TPROC-H build FK error
  src/mariadb/mariaolap.tcl
  src/mysql/mysqlolap.tcl
Labels: bug

#602 Add MariaDB/MySQL No Stored Procedures option to TPROC-C
  config/mariadb.xml
  config/mysql.xml
  src/mariadb/mariaoltp.tcl
  src/mariadb/mariaopt.tcl
  src/mysql/mysqloltp.tcl
  src/mysql/mysqlopt.tcl
Labels: enhancement

#611 Implement BCP Option for MSSQLS TPCH Load
  config/mssqlserver.xml
  modules/tpchcommon-1.0.tm
  src/mssqlserver/mssqlsolap.tcl
  src/mssqlserver/mssqlsopt.tcl
Labels: enhancement, database, build

#620 Update Documentation for v4.9
  DocBook/docs.xml
  DocBook/docs/images/ch1-10.PNG
  DocBook/docs/images/ch1-11.PNG
  DocBook/docs/images/ch1-12.PNG
  DocBook/docs/images/ch1-12aa.PNG
  DocBook/docs/images/ch1-12aaa.PNG
  DocBook/docs/images/ch1-17.PNG
  DocBook/docs/images/ch1-17aa.PNG
  DocBook/docs/images/ch1-4a.PNG
  DocBook/docs/images/ch1-6.PNG
  DocBook/docs/images/ch1-8.PNG
  DocBook/docs/images/ch1-9.PNG
  DocBook/docs/images/ch13-5.PNG
  DocBook/docs/images/ch2-6.PNG
  DocBook/docs/images/ch4-15p.PNG
  DocBook/docs/images/ch4-5.PNG
  DocBook/docs/images/ch4-7.PNG
  DocBook/docs/images/ch4-7a.PNG
  DocBook/docs/images/ch7-10.png
  DocBook/docs/images/ch9-9.PNG
Labels: Documentation

#626 Version bump to 4.9
  Docker/base/Dockerfile
Labels: docker
