Repository TPC-Council/HammerDB, pull requests merged in 2023-11, with the labels that each got.

#638 Fix call ash_fetch,error on Windows client running PostgreSQL metrics
  src/postgresql/pgmet.tcl
Labels: bug, metric, database

#641 Docker cloudtk
  Docker/cloudtk/Dockerfile
  Docker/cloudtk/Readme.md
Labels: gui, docker

#644 Add check to vurun for pre-existing threads
  src/generic/gencli.tcl
Labels: bug

#642 Add optional purge and write back for MariaDB TPROC-C
  config/mariadb.xml
  src/mariadb/mariaoltp.tcl
  src/mariadb/mariaopt.tcl
Labels: enhancement, database

#646 Add giset command to set generic dictionary settings
  src/generic/gencli.tcl
  src/generic/genhelp.tcl
Labels: enhancement
