Repository TPC-Council/HammerDB, pull requests merged in 2024-10, with the labels that each got.

#750 Add indexes to orders table for SQL TPROC-H partitioned row store
  src/mssqlserver/mssqlsolap.tcl
Labels: bug, database

#761 Docker version bump to 4.12
  Docker/base/Dockerfile
Labels: docker

#752 MSSQL TPCH Load does not work for Single User
  src/mssqlserver/mssqlsolap.tcl
Labels: bug, database, build

#759 Add keepalive to datagenrun
  src/generic/gencli.tcl
Labels: bug, datagen

#754 Add awbreezedark theme option to GUI
  images/icons.tcl
  modules/emu_graph-2.0.tm
  modules/tkcon-2.7.10.tm
  src/generic/gened.tcl
  src/generic/genmetrics.tcl
  src/generic/genmodes.tcl
  src/generic/gentab.tcl
  src/generic/gentc.tcl
  src/generic/gentheme.tcl
  src/generic/genvu.tcl
  src/oracle/oramet.tcl
  src/postgresql/pgmet.tcl
Labels: enhancement, gui
